language: node_js
node_js: node
services:
- mongodb
before_script: chmod 0777 ./node_modules/.bin/_mocha
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: KZZvtQyh0gndyM7VETfki+C88C3ifZ64E9HTMWF0wL5PG7mGnBuVscoyt9ZV/3VWdpC2WgU9iBdoz1DlmvoaeCiAUfFtzeICW0aisABgKkhDWbub34gPPxwohye6IN2DaSn2ZaH7UnBcf+qcqjLUCZTAvF9rTwaDTCjSAlA2fMDzP+ANGNd96heAdHotYHF0vtJe2ouzd5Q5DyHwratjFjUAl4hRgx7GpiUZEUG1yQhhH8/O2yF/rHiA570dm+1oxpwVBD6SJpP2UaF3d2IyCnde97HON+sgW6klGwSSsxh75dtdOjDBTUTE3jDtOZQh9JVKK9vRWgbyi7/veOXYdm+7/LR8c3qDsuHIbcphfDiZr8O0EV4vac4Ol4i3tXYn6WIHjwiOM2Nl5aJW+yU79rEuZ/jumcvUQ5siNaCKgWFdc3HA3Uborg6sNwxMWPOIUaeL+8q4me/GSRmvMup5r2O3GexzGr4e67UtR35SOW7x7SY75zJ9ohdMVhiPUdr1n+rSxD4GcBJb2z+6NddzI2rvaSg21S7FcUX9KJZocaTXD2lHS7+ky5vq/mOAlNMp8C+TXTgePDDmOb5WHGWjwBW/qzJ3DXu4+C9iwPKM8NrP8dMY4B97Gz7Y1C2jK/5O9HX4EBTQmOFflyp4oq7zCwvxT2uqhzb9drXwjd+DICE=
  app: mongoshoppinglistapp
  on:
    repo: hnnguyen45thinkful/mongo-shopping-list
